config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about' =>'home#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update,:create,:destroy]
  resources :books,only: [:index,:edit,:show,:update,:create,:destroy] do
  	resource :favorites,only: [:create,:destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  
  
  
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments,dependent: :destroy
	
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
  def show
  	@book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @user = current_user
    @book = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id =current_user.id

  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      @user = current_user
      @books = Book.all
  		render :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if user_signed_in? && current_user.id == @book.user_id
       render :edit
    else
       redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def user_params
    params.require(:user).permit(:username,:profile,:profile_image)

  end

  def book_params
  	params.require(:book).permit(:title,:body,:user_id)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<% book_comments.each do |book_comment| %>
	<li id="comment-container">
		<div class='comment-box'>
			<div class="comment-avatar">
				<%= attachment_image_tag book_comment.user, :profile_image,:fill, 40, 40, fallback: 'no_image.jpg' %>
				<%= book_comment.content %>
					<% if book_comment.user == current_user %>
						<%= link_to "Destroy",book_book_comment_path(@book,book_comment), method: :delete,  class: "btn-sm btn-danger destroy_book_#{@book.id}" %>

					<% end %>
			</div>
			<div class='comment-text'>
				<p><%= link_to "#{book_comment.user.name}",user_path(book_comment.user.id) %></p>
			</div>
		</div>
	</li>
<% end %> 

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<%if @book.errors.any? %>
		<div class="alert alert-warning">
            <h2><%= @book.errors.count %>error</h2>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			</ul>
		</div>
		<% end %>
<% end %>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%if @book.errors.any? %>
		<div class="alert alert-warning">
		<h2><%= @book.errors.count %>error</h2>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			</ul>
		</div>
			<% end %>
		<% end %>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th><colspan="3"></th>
					<th><colspan='4'></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

					<td>
						<% if current_user.already_favorited_by?(book)%>
						<li>
							<%= link_to book_favorites_path(book), method: :delete do %>
								<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
							
							<% end %>
							<%= book.favorites.count %>
						</li>
						<% else %>
						<li>
							<%= link_to book_favorites_path(book),method: :post do %>
								
								<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>

							<% end %>
							
							<%= book.favorites.count %>
						</li>
						<% end %>
					</td>
					<td>
						コメント数　: <%= @book_comments.count %>
					</td>
				</tr>
				<% end %>
				
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile',user: @user%>

		<h2>New book</h2>
		<%if @book.errors.any? %>
		<div class="alert alert-warning">
		<h2><%= @book.errors.count %>error</h2>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			</ul>
		</div>
			<% end %>
		<% end %>
		<%= render 'books/newform',book: @book%>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

					<td>
						<% if current_user.already_favorited_by?(@book) %>
							<%= link_to book_favorites_path(@book),method: :delete do %>
							<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
							<%= @book.favorites.count %>
							<% end %>
						<% else %>
							<%= link_to book_favorites_path(@book), method: :create do %>
							<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
							<%= @book.favorites.count %>
							<% end %>

						<% end %>

					</td>
					<td>
						コメント数　: <%= @book_comments.count %>
					</td>

					<% if @book.user.id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
				<tr>
					<td>
						<li id="comment_area">
							<%= render partial: 'index',locals: {book_comments: @book_comments} %>
						</li>
						<% if user_signed_in? %>
							<div class="comment-create">
								<%= render partial: 'book_comments/form', locals: {book_comment: @book_comment, book: @book} %>
							</div>
						<% end %>
					</td>
				</tr>
			</table>

	</div>
</div>